### PR TITLE
downgrade deps for use with exq

### PR DESCRIPTION
**Pull request by colbyh**
:-1:

### CODE REVIEW

**Comment by bitwalker** [comment]
Two solutions here:
1. `exq` updates it's Timex dependency (looking through the source this can be done without any code changes)
2. You override the Timex dependency with `{:timex, "~> 0.18", override: true}` in your project's mix.exs.

**Comment by colbyh** [comment]
accidental PR :-)

updating the Exq dep would be infinitely preferable but it causes a couple of their tests to blow up. overriding locally seems to be a better option for the moment, gracias for the heads up!

**Comment by bitwalker** [comment]
@colbyh I'll take a look at the exq repo and see if I can get a PR working for it :)

**Comment by bitwalker** [comment]
@colbyh What failures were you seeing with `exq`? Looks to me like all the tests pass with both 0.13.5 and 0.18.0 (though there are some errors output to the console, the same errors are present in both versions, and don't appear to have anything to do with timex, and don't result in any test failures).

**Pull request closed without merging**
